// ── V1 Contracts ──
export const SCHEMA_VERSION = 1 as const;

// Common
export {
  TokenUsageSchema,
  ArtifactSchema,
  EvalResultSchema,
  ProviderSchema,
  QuotaWindowSchema,
  AggregateTypeSchema,
} from './common.js';
export type {
  TokenUsage,
  Artifact,
  EvalResult,
  Provider,
  QuotaWindow,
  AggregateType,
} from './common.js';

// Events
export {
  BaseEventSchema,
  EventSchema,
  SessionCreatedEventSchema,
  SessionStartedEventSchema,
  SessionOutputEventSchema,
  SessionCompletedEventSchema,
  SessionFailedEventSchema,
  SessionApprovalRequestedEventSchema,
  SessionApprovalResolvedEventSchema,
  TaskCreatedEventSchema,
  TaskAssignedEventSchema,
  TaskStartedEventSchema,
  TaskCompletedEventSchema,
  TaskFailedEventSchema,
  AgentRegisteredEventSchema,
  AgentHealthCheckedEventSchema,
  AgentQuotaConsumedEventSchema,
  RunCreatedEventSchema,
  RunProgressEventSchema,
  RunDiffProducedEventSchema,
  RunCompletedEventSchema,
  IssueCreatedEventSchema,
  IssueStatusChangedEventSchema,
  IssueCommentAddedEventSchema,
  ApprovalRequestedEventSchema,
  ApprovalResolvedEventSchema,
  KnowledgeCreatedEventSchema,
  KnowledgePromotedEventSchema,
  KnowledgeDriftDetectedEventSchema,
  PolicyEvaluatedEventSchema,
  SystemQuotaWarningEventSchema,
  SystemQuotaExhaustedEventSchema,
  SystemFreezeActivatedEventSchema,
  SystemFreezeDeactivatedEventSchema,
} from './events.js';
export type {
  BaseEvent,
  Event,
  SessionCreatedEvent,
  SessionStartedEvent,
  SessionOutputEvent,
  SessionCompletedEvent,
  SessionFailedEvent,
  SessionApprovalRequestedEvent,
  SessionApprovalResolvedEvent,
  TaskCreatedEvent,
  TaskAssignedEvent,
  TaskStartedEvent,
  TaskCompletedEvent,
  TaskFailedEvent,
  AgentRegisteredEvent,
  AgentHealthCheckedEvent,
  AgentQuotaConsumedEvent,
  RunCreatedEvent,
  RunProgressEvent,
  RunDiffProducedEvent,
  RunCompletedEvent,
  IssueCreatedEvent,
  IssueStatusChangedEvent,
  IssueCommentAddedEvent,
  ApprovalRequestedEvent,
  ApprovalResolvedEvent,
  KnowledgeCreatedEvent,
  KnowledgePromotedEvent,
  KnowledgeDriftDetectedEvent,
  PolicyEvaluatedEvent,
  SystemQuotaWarningEvent,
  SystemQuotaExhaustedEvent,
  SystemFreezeActivatedEvent,
  SystemFreezeDeactivatedEvent,
} from './events.js';

// Commands
export {
  BaseCommandSchema,
  CommandSchema,
  SessionCreateCommandSchema,
  SessionAttachCommandSchema,
  SessionApproveCommandSchema,
  SessionKillCommandSchema,
  SessionSendInputCommandSchema,
  TaskCreateCommandSchema,
  TaskAssignCommandSchema,
  TaskCancelCommandSchema,
  IssueCreateCommandSchema,
  IssueUpdateCommandSchema,
  ApprovalResolveCommandSchema,
  KnowledgeCreateCommandSchema,
  KnowledgePromoteCommandSchema,
  SystemFreezeCommandSchema,
  SystemUnfreezeCommandSchema,
} from './commands.js';
export type {
  BaseCommand,
  Command,
  SessionCreateCommand,
  SessionAttachCommand,
  SessionApproveCommand,
  SessionKillCommand,
  SessionSendInputCommand,
  TaskCreateCommand,
  TaskAssignCommand,
  TaskCancelCommand,
  IssueCreateCommand,
  IssueUpdateCommand,
  ApprovalResolveCommand,
  KnowledgeCreateCommand,
  KnowledgePromoteCommand,
  SystemFreezeCommand,
  SystemUnfreezeCommand,
} from './commands.js';

// Context Packet
export { ContextPacketSchema } from './context-packet.js';
export type { ContextPacket } from './context-packet.js';
