from __future__ import annotations

from typing import Any, Protocol

from .contracts import CommandEnvelope, ContextPacket


class AgentRuntimePort(Protocol):
    def launch_run(self, packet: ContextPacket) -> str: ...
    def observe_run(self, run_id: str) -> dict[str, Any]: ...
    def attach_run(self, run_id: str) -> None: ...


class KnowledgePort(Protocol):
    def read(self, uri: str) -> str: ...
    def write(self, uri: str, content: str) -> None: ...


class GovernancePort(Protocol):
    def create_issue(self, title: str, body: str) -> str: ...
    def request_approval(self, command: CommandEnvelope) -> bool: ...


class ModelProviderPort(Protocol):
    def invoke(self, *, provider: str, model: str, prompt: str) -> str: ...
